spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olap
    username: olap
    password: olap
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/reports-realm

server:
  port: 8000